export { Home } from "./home/Home.jsx"
export { AvailableProjects } from "./projects/AvailableProjects.jsx" 
export { Profile } from "./profile/Profile.jsx"
export { Register } from "./register/Register"
export { Login } from "./login/Login.jsx"
export { DeleteProject } from "./projects/DeleteProject.jsx"
export { UpdateProject } from "./projects/UpdateProject.jsx"
export { UploadProject } from "./projects/UploadProject.jsx"
export { UpdateObservation } from "./observations/UpdateObservation.jsx"
export { DeleteObservation } from "./observations/DeleteObservation.jsx"
export { UploadObservation } from "./observations/UploadObservation.jsx"

export { ProjectsTable } from "./admin/projects/ProjectsTable.jsx"
export { DeleteProjectAdmin } from "./admin/projects/DeleteProjectAdmin.jsx"
export { UploadProjectAdmin } from "./admin/projects/UploadProjectAdmin.jsx"
export { DetailProjectAdmin } from "./admin/projects/DetailProjectAdmin.jsx"
export { UpdateProjectAdmin } from "./admin/projects/UpdateProjectAdmin.jsx"
export { UsersTable } from "./admin/users/UsersTable.jsx"
export { DeleteUser } from "./admin/users/DeleteUser.jsx"
export { User } from "./admin/users/User.jsx"
export { UploadUser } from "./admin/users/UploadUser.jsx"
export { UpdateUser } from "./admin/users/UpdateUser.jsx"

export * from './detail/index.js'