export { Home } from "./home/Home.jsx"
export { AvailableProjects } from "./projects/AvailableProjects.jsx" 
export { Profile } from "./profile/Profile.jsx"
export { UpdateUserProfile } from "./profile/UpdateUserProfile.jsx"
export { Register } from "./register/Register"
export { RegisterAdmin } from "./register/RegisterAdmin.jsx"
export { Login } from "./login/Login.jsx"
export { DeleteProject } from "./projects/DeleteProject.jsx"
export { UpdateProject } from "./projects/UpdateProject.jsx"
export { UploadProject } from "./projects/UploadProject.jsx"
export { UpdateObservation } from "./observations/UpdateObservation.jsx"
export { DeleteObservation } from "./observations/DeleteObservation.jsx"
export { UploadObservation } from "./observations/UploadObservation.jsx"

export { ProjectsTable } from "./admin/projects/ProjectsTable.jsx"
export { Remunerados } from "./admin/projects/Remunerados.jsx"
export { DetailProjectRemunerado } from "./admin/projects/DetailProjectRemunerado.jsx"
export { ListTesters } from "./admin/projects/ListTesters.jsx"
export { AsignacionTesteo } from "./admin/projects/AsignacionTesteo.jsx"
export { DetalleSolicitudTesteo } from "./admin/projects/DetalleSolicitudTesteo.jsx"


export { DeleteProjectAdmin } from "./admin/projects/DeleteProjectAdmin.jsx"
export { UploadProjectAdmin } from "./admin/projects/UploadProjectAdmin.jsx"
export { DetailProjectAdmin } from "./admin/projects/DetailProjectAdmin.jsx"
export { UpdateProjectAdmin } from "./admin/projects/UpdateProjectAdmin.jsx"
export { UsersTable } from "./admin/users/UsersTable.jsx"
export { DeleteUser } from "./admin/users/DeleteUser.jsx"
export { User } from "./admin/users/User.jsx"
export { AddUser } from "./admin/users/AddUser.jsx"
export { SolicitudAmistadRecibida } from "./profile/SolicitudAmistadRecibida.jsx"
export { SolicitudAmistadEnviada } from "./profile/SolicitudAmistadEnviada.jsx"
export { SolicitudColaboracionRecibida } from "./profile/SolicitudColaboracionRecibida.jsx"
export { SolicitudColaboracionEnviada } from "./profile/SolicitudColaboracionEnviada.jsx"
export { SolicitudProyectoCerrado } from "./projects//SolicitudProyectoCerrado.jsx"


export { UploadUser } from "./admin/users/UploadUser.jsx"
export { UpdateUser } from "./admin/users/UpdateUser.jsx"

export * from './detail/index.js'